In [1]:
import numpy as np
from scipy.optimize import linprog

# Define the 5x5 payoff matrix for Player 1
payoff_matrix = np.array([
    [3, 1, 2, 5, 0],
    [1, 4, 3, 0, -2],
    [2, 5, 0, 3, 1],
    [6, 1, -1, 2, -3],
    [0, 2, 3, 1, 4]
])

# --- Player 1 (Row Player) ---
# Variables: [p1, p2, ..., p5, v] where p1...p5 are probabilities and v is the game's value
n_rows, n_cols = payoff_matrix.shape
c = np.zeros(n_rows + 1)
c[-1] = -1  # Maximize v (negative because linprog minimizes)

A_ub = np.hstack([-payoff_matrix.T, np.ones((n_cols, 1))])  # -A^T p + v >= 0
b_ub = np.zeros(n_cols)

A_eq = np.hstack([np.ones((1, n_rows)), [[0]]])  # Sum of probabilities = 1
b_eq = [1]

bounds = [(0, 1)] * n_rows + [(None, None)]  # Probabilities between 0 and 1, v unbounded

# Solve for Player 1
result_player_1 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='highs')
mixed_strategy_player_1 = result_player_1.x[:-1]
game_value = result_player_1.x[-1]

# --- Player 2 (Column Player) ---
# Variables: [q1, q2, ..., q5, v] where q1...q5 are probabilities and v is the game's value
c = np.zeros(n_cols + 1)
c[-1] = 1  # Minimize v

A_ub = np.hstack([payoff_matrix, -np.ones((n_rows, 1))])  # A q - v <= 0
b_ub = np.zeros(n_rows)

A_eq = np.hstack([np.ones((1, n_cols)), [[0]]])  # Sum of probabilities = 1
b_eq = [1]

bounds = [(0, 1)] * n_cols + [(None, None)]  # Probabilities between 0 and 1, v unbounded

# Solve for Player 2
result_player_2 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='highs')
mixed_strategy_player_2 = result_player_2.x[:-1]

# Display Results
print("Mixed Strategy for Player 1 (Row Player):", mixed_strategy_player_1)
print("Mixed Strategy for Player 2 (Column Player):", mixed_strategy_player_2)
print("Game Value (v):", game_value)

Mixed Strategy for Player 1 (Row Player): [0.12021858 0.         0.04918033 0.22404372 0.60655738]
Mixed Strategy for Player 2 (Column Player): [0.47540984 0.04918033 0.         0.06557377 0.40983607]
Game Value (v): 1.8032786885245904


In [3]:
import numpy as np

# Player 1's strategies (cards played in each round)
player1_strategies = [
    [4, 0, 0], [3, 1, 0], [3, 0, 1], [2, 2, 0], [2, 1, 1],
    [2, 0, 2], [1, 3, 0], [1, 2, 1], [1, 1, 2], [1, 0, 3],
    [0, 4, 0], [0, 3, 1], [0, 2, 2], [0, 1, 3], [0, 0, 4]
]

# Player 2's strategies (cards played in each round)
player2_strategies = [
    [3, 0, 0], [2, 1, 0], [2, 0, 1], [1, 2, 0], [1, 1, 1],
    [1, 0, 2], [0, 3, 0], [0, 2, 1], [0, 1, 2], [0, 0, 3]
]

# Calculate payoffs: Sum of (Player 1 card - Player 2 card) in each round
payoff_matrix = np.zeros((len(player1_strategies), len(player2_strategies)))

for i, p1 in enumerate(player1_strategies):
    for j, p2 in enumerate(player2_strategies):
        payoff_matrix[i, j] = sum(max((p1[p] - p2[p]), 0) for p in range(3))

payoff_matrix

array([[1., 2., 2., 3., 3., 3., 4., 4., 4., 4.],
       [1., 1., 2., 2., 2., 3., 3., 3., 3., 4.],
       [1., 2., 1., 3., 2., 2., 4., 3., 3., 3.],
       [2., 1., 2., 1., 2., 3., 2., 2., 3., 4.],
       [2., 1., 1., 2., 1., 2., 3., 2., 2., 3.],
       [2., 2., 1., 3., 2., 1., 4., 3., 2., 2.],
       [3., 2., 3., 1., 2., 3., 1., 2., 3., 4.],
       [3., 2., 2., 1., 1., 2., 2., 1., 2., 3.],
       [3., 2., 2., 2., 1., 1., 3., 2., 1., 2.],
       [3., 3., 2., 3., 2., 1., 4., 3., 2., 1.],
       [4., 3., 4., 2., 3., 4., 1., 2., 3., 4.],
       [4., 3., 3., 2., 2., 3., 1., 1., 2., 3.],
       [4., 3., 3., 2., 2., 2., 2., 1., 1., 2.],
       [4., 3., 3., 3., 2., 2., 3., 2., 1., 1.],
       [4., 4., 3., 4., 3., 2., 4., 3., 2., 1.]])

In [6]:
player1_strategies

[[4, 0, 0],
 [3, 1, 0],
 [3, 0, 1],
 [2, 2, 0],
 [2, 1, 1],
 [2, 0, 2],
 [1, 3, 0],
 [1, 2, 1],
 [1, 1, 2],
 [1, 0, 3],
 [0, 4, 0],
 [0, 3, 1],
 [0, 2, 2],
 [0, 1, 3],
 [0, 0, 4]]

In [4]:
# Payoff matrix for the game
payoff_matrix = np.array([
    [1., 2., 2., 3., 3., 3., 4., 4., 4., 4.],
    [1., 1., 2., 2., 2., 3., 3., 3., 3., 4.],
    [1., 2., 1., 3., 2., 2., 4., 3., 3., 3.],
    [2., 1., 2., 1., 2., 3., 2., 2., 3., 4.],
    [2., 1., 1., 2., 1., 2., 3., 2., 2., 3.],
    [2., 2., 1., 3., 2., 1., 4., 3., 2., 2.],
    [3., 2., 3., 1., 2., 3., 1., 2., 3., 4.],
    [3., 2., 2., 1., 1., 2., 2., 1., 2., 3.],
    [3., 2., 2., 2., 1., 1., 3., 2., 1., 2.],
    [3., 3., 2., 3., 2., 1., 4., 3., 2., 1.],
    [4., 3., 4., 2., 3., 4., 1., 2., 3., 4.],
    [4., 3., 3., 2., 2., 3., 1., 1., 2., 3.],
    [4., 3., 3., 2., 2., 2., 2., 1., 1., 2.],
    [4., 3., 3., 3., 2., 2., 3., 2., 1., 1.],
    [4., 4., 3., 4., 3., 2., 4., 3., 2., 1.]
])

# Find dominated strategies for Player 1 (row player)
def find_dominated_strategies(payoff_matrix):
    dominated_rows = set()
    rows, cols = payoff_matrix.shape
    for i in range(rows):
        for j in range(rows):
            if i != j and not any(payoff_matrix[i] > payoff_matrix[j]):
                dominated_rows.add(i)
    return list(dominated_rows)

# Find dominated strategies for Player 2 (column player)
def find_dominated_columns(payoff_matrix):
    dominated_cols = set()
    rows, cols = payoff_matrix.shape
    for i in range(cols):
        for j in range(cols):
            if i != j and not any(payoff_matrix[:,i] > payoff_matrix[:,j]):
                dominated_cols.add(i)
    return list(dominated_cols)

# Find dominated strategies
dominated_rows = find_dominated_strategies(payoff_matrix)
dominated_cols = find_dominated_columns(payoff_matrix)

# Remove dominated strategies
reduced_payoff_matrix = np.delete(payoff_matrix, dominated_rows, axis=0)
reduced_payoff_matrix = np.delete(reduced_payoff_matrix, dominated_cols, axis=1)

reduced_payoff_matrix

array([[1., 2., 2., 3., 3., 3., 4., 4., 4., 4.],
       [2., 1., 2., 1., 2., 3., 2., 2., 3., 4.],
       [2., 1., 1., 2., 1., 2., 3., 2., 2., 3.],
       [2., 2., 1., 3., 2., 1., 4., 3., 2., 2.],
       [3., 2., 2., 1., 1., 2., 2., 1., 2., 3.],
       [3., 2., 2., 2., 1., 1., 3., 2., 1., 2.],
       [4., 3., 4., 2., 3., 4., 1., 2., 3., 4.],
       [4., 3., 3., 2., 2., 2., 2., 1., 1., 2.],
       [4., 4., 3., 4., 3., 2., 4., 3., 2., 1.]])

In [7]:
reduced_player1_strategies = np.delete(player1_strategies, dominated_rows, axis=0)
reduced_player2_strategies = np.delete(player2_strategies, dominated_cols, axis=1)
reduced_player1_strategies

array([[4, 0, 0],
       [2, 2, 0],
       [2, 1, 1],
       [2, 0, 2],
       [1, 2, 1],
       [1, 1, 2],
       [0, 4, 0],
       [0, 2, 2],
       [0, 0, 4]])

In [15]:
from scipy.optimize import linprog

# Number of strategies for each player
m = len(player1_strategies)
n = len(player2_strategies)

# Linear programming formulation:
# Maximize the expected payoff for Player 1
# Constraints: x_i should sum to 1 and be between 0 and 1

# Set up the objective function (negative since linprog minimizes)
c = -np.ones(m)  # We aim to maximize the payoff

# Set up the inequality constraints (probabilities must sum to 1)
A_eq = np.ones((1, m))  # Sum of probabilities for Player 1's strategies must be 1
b_eq = np.array([1])

# Bounds for Player 1's probabilities
bounds = [(0, 1)] * m

# Solve using linprog
result = linprog(c, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='highs')

# Player 1's optimal mixed strategy
player1_mixed_strategy = result.x

# Now for Player 2's strategy
# Minimize the expected payoff for Player 2 (maximize the negative)
c2 = np.ones(n)

# Constraints for Player 2
A_eq2 = np.ones((1, n))
b_eq2 = np.array([1])

# Bounds for Player 2's probabilities
bounds2 = [(0, 1)] * n

# Solve for Player 2's optimal mixed strategy
result2 = linprog(c2, A_eq=A_eq2, b_eq=b_eq2, bounds=bounds2, method='highs')

# Player 2's optimal mixed strategy
player2_mixed_strategy = result2.x

player1_mixed_strategy, player2_mixed_strategy

(array([ 1., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.]),
 array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [48]:
n_rows, n_cols = reduced_payoff_matrix.shape
c = np.zeros(n_rows + 1)
c[-1] = -1  # Maximize v (negative because linprog minimizes)

A_ub = np.hstack([-reduced_payoff_matrix.T, np.ones((n_cols, 1))])  # -A^T p + v >= 0
b_ub = np.zeros(n_cols)

A_eq = np.hstack([np.ones((1, n_rows)), [[0]]])  # Sum of probabilities = 1
b_eq = [1]

bounds = [(0, 1)] * n_rows + [(None, None)]  # Probabilities between 0 and 1, v unbounded

# Solve for Player 1
result_player_1 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='interior-point')
mixed_strategy_player_1 = result_player_1.x[:-1]
game_value = result_player_1.x[-1]

# --- Player 2 (Column Player) ---
# Variables: [q1, q2, ..., q5, v] where q1...q5 are probabilities and v is the game's value
c = np.zeros(n_cols + 1)
c[-1] = 1  # Minimize v

A_ub = np.hstack([reduced_payoff_matrix, -np.ones((n_rows, 1))])  # A q - v <= 0
b_ub = np.zeros(n_rows)

A_eq = np.hstack([np.ones((1, n_cols)), [[0]]])  # Sum of probabilities = 1
b_eq = [1]

bounds = [(0, 1)] * n_cols + [(None, None)]  # Probabilities between 0 and 1, v unbounded

# Solve for Player 2
result_player_2 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='interior-point')
mixed_strategy_player_2 = result_player_2.x[:-1]

# Display Results
print("Mixed Strategy for Player 1 (Row Player):", mixed_strategy_player_1)
print("Mixed Strategy for Player 2 (Column Player):", mixed_strategy_player_2)
print("Game Value (v):", game_value)

Mixed Strategy for Player 1 (Row Player): [3.33333335e-01 8.08461373e-10 2.76772397e-09 8.08461642e-10
 2.76772461e-09 2.76772416e-09 3.33333335e-01 8.08461476e-10
 3.33333335e-01]
Mixed Strategy for Player 2 (Column Player): [0.12935777 0.08871148 0.08871148 0.08871148 0.07965781 0.08871148
 0.12935777 0.08871148 0.08871148 0.12935777]
Game Value (v): 2.999999993549847


C:\Users\liusc\AppData\Local\Temp\ipykernel_46112\3394872550.py:14: DeprecationWarning: `method='interior-point'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  result_player_1 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='interior-point')
C:\Users\liusc\AppData\Local\Temp\ipykernel_46112\3394872550.py:32: DeprecationWarning: `method='interior-point'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  result_player_2 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='interior-point')


In [32]:
sum(mixed_strategy_player_1)

1.0000000149937767

In [52]:
n_rows, n_cols = reduced_payoff_matrix.shape
c = np.zeros(n_rows + 1)
c[-1] = -1  # Maximize v (negative because linprog minimizes)

A_ub = np.hstack([-reduced_payoff_matrix.T, np.ones((n_cols, 1))])  # -A^T p + v >= 0
b_ub = np.zeros(n_cols)

A_eq = np.hstack([np.ones((1, n_rows)), [[0]]])  # Sum of probabilities = 1
b_eq = [1]

bounds = [(0, 1)] * n_rows + [(None, None)]  # Probabilities between 0 and 1, v unbounded

# Solve for Player 1
result_player_1 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='revised simplex')
mixed_strategy_player_1 = result_player_1.x[:-1]
game_value = result_player_1.x[-1]

# --- Player 2 (Column Player) ---
# Variables: [q1, q2, ..., q5, v] where q1...q5 are probabilities and v is the game's value
c = np.zeros(n_cols + 1)
c[-1] = 1  # Minimize v

A_ub = np.hstack([reduced_payoff_matrix, -np.ones((n_rows, 1))])  # A q - v <= 0
b_ub = np.zeros(n_rows)

A_eq = np.hstack([np.ones((1, n_cols)), [[0]]])  # Sum of probabilities = 1
b_eq = [1]

bounds = [(0, 1)] * n_cols + [(None, None)]  # Probabilities between 0 and 1, v unbounded

# Solve for Player 2
result_player_2 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='revised simplex')
mixed_strategy_player_2 = result_player_2.x[:-1]

# Display Results
print("Mixed Strategy for Player 1 (Row Player):", mixed_strategy_player_1)
print("Mixed Strategy for Player 2 (Column Player):", mixed_strategy_player_2)
print("Game Value (v):", game_value)

Mixed Strategy for Player 1 (Row Player): [0.33333333 0.         0.         0.         0.         0.
 0.33333333 0.         0.33333333]
Mixed Strategy for Player 2 (Column Player): [0.16666667 0.         0.         0.         0.         0.5
 0.33333333 0.         0.         0.        ]
Game Value (v): 3.0


C:\Users\liusc\AppData\Local\Temp\ipykernel_46112\3523312597.py:14: DeprecationWarning: `method='revised simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  result_player_1 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='revised simplex')
C:\Users\liusc\AppData\Local\Temp\ipykernel_46112\3523312597.py:32: DeprecationWarning: `method='revised simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  result_player_2 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='revised simplex')


In [51]:
n_rows, n_cols = reduced_payoff_matrix.shape
c = np.zeros(n_rows + 1)
c[-1] = -1  # Maximize v (negative because linprog minimizes)

A_ub = np.hstack([-reduced_payoff_matrix.T, np.ones((n_cols, 1))])  # -A^T p + v >= 0
b_ub = np.zeros(n_cols)

A_eq = np.hstack([np.ones((1, n_rows)), [[0]]])  # Sum of probabilities = 1
b_eq = [1]

bounds = [(0, 1)] * n_rows + [(None, None)]  # Probabilities between 0 and 1, v unbounded

# Solve for Player 1
result_player_1 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds)
mixed_strategy_player_1 = result_player_1.x[:-1]
game_value = result_player_1.x[-1]

# --- Player 2 (Column Player) ---
# Variables: [q1, q2, ..., q5, v] where q1...q5 are probabilities and v is the game's value
c = np.zeros(n_cols + 1)
c[-1] = 1  # Minimize v

A_ub = np.hstack([reduced_payoff_matrix, -np.ones((n_rows, 1))])  # A q - v <= 0
b_ub = np.zeros(n_rows)

A_eq = np.hstack([np.ones((1, n_cols)), [[0]]])  # Sum of probabilities = 1
b_eq = [1]

bounds = [(0, 1)] * n_cols + [(None, None)]  # Probabilities between 0 and 1, v unbounded

# Solve for Player 2
result_player_2 = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds)
mixed_strategy_player_2 = result_player_2.x[:-1]

# Display Results
print("Mixed Strategy for Player 1 (Row Player):", mixed_strategy_player_1)
print("Mixed Strategy for Player 2 (Column Player):", mixed_strategy_player_2)
print("Game Value (v):", game_value)

Mixed Strategy for Player 1 (Row Player): [0.33333333 0.         0.         0.         0.         0.
 0.33333333 0.         0.33333333]
Mixed Strategy for Player 2 (Column Player): [0.33333333 0.         0.         0.         0.         0.
 0.         0.5        0.         0.16666667]
Game Value (v): 3.0


In [53]:
import matplotlib.pyplot as plt
plt.figure(figsize=(8, 6))
plt.imshow(payoff_matrix, cmap='viridis', interpolation='nearest')
plt.colorbar(label="Payoff Value")
plt.title("Payoff Matrix Heatmap")
plt.xlabel("Strategies (Columns)")
plt.ylabel("Strategies (Rows)")
plt.show()

ImportError: DLL load failed while importing _path: 找不到指定的模块。